export const START_FETCH_ROOMS = 'START_FETCH_ROOMS';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_FAILED  = 'FETCH_ROOMS_FAILED';

export const START_FETCH_ROOM_INFO = 'START_FETCH_ROOM_INFO';
export const FETCH_ROOM_INFO_SUCCESS = 'FETCH_ROOM_INFO_SUCCESS';
export const FETCH_ROOM_INFO_FAILED = 'FETCH_ROOM_INFO_FAILED';
export const UPDATE_ROOM_BOOK = 'UPDATE_ROOM_BOOK';

export const START_BOOKING_ROOM = 'START_BOOKING_ROOM';
export const BOOKING_ROOM_SUCCESS = 'BOOKING_ROOM_SUCCESS';
export const BOOKING_ROOM_FAILED = 'BOOKING_ROOM_FAILED';
