export const START_FETCH_ROOMS = 'START_FETCH_ROOMS';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_FAILED  = 'FETCH_ROOMS_FAILED';

export const START_FETCH_ROOM_INFO = 'START_FETCH_ROOM_INFO';
export const FETCH_ROOM_INFO_SUCCESS = 'FETCH_ROOM_INFO_SUCCESS';
export const FETCH_ROOM_INFO_FAILED = 'FETCH_ROOM_INFO_FAILED';
